# Generated by Django 5.2.1 on 2025-06-23 02:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100, verbose_name='sensor name')),
                ('sensor_type', models.CharField(choices=[('METHANE', 'Methane'), ('CARBON_MONOXIDE', 'Carbon Monoxide'), ('PROPANE', 'Propane'), ('BUTANE', 'Butane')], max_length=50, verbose_name='sensor type')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='serial number')),
                ('installation_date', models.DateField(verbose_name='installation date')),
                ('last_calibration_date', models.DateField(verbose_name='last calibration date')),
                ('battery_level_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='battery level')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'gas sensor',
                'verbose_name_plural': 'gas sensors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='phone number')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='city')),
                ('state_province', models.CharField(blank=True, default='', max_length=100, verbose_name='state/province')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='country')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='newsletter subscribed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Admin Login'), ('USER_EDIT', 'User Edited'), ('SENSOR_EDIT', 'Sensor Edited'), ('ALERT_RESOLVE', 'Alert Resolved')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin activity log',
                'verbose_name_plural': 'admin activity logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150, verbose_name='contact name')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('relationship', models.CharField(choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('NEIGHBOR', 'Neighbor'), ('LANDLORD', 'Landlord'), ('OTHER', 'Other')], max_length=20, verbose_name='relationship')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='primary contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'emergency contact',
                'verbose_name_plural': 'emergency contacts',
                'ordering': ['-is_primary_contact', 'contact_name'],
            },
        ),
        migrations.CreateModel(
            name='GasRefillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refill amount')),
                ('refill_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refill cost')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='supplier name')),
                ('refill_date', models.DateField(verbose_name='refill date')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_refills', to='mynewapp.gassensor')),
            ],
            options={
                'verbose_name': 'gas refill record',
                'verbose_name_plural': 'gas refill records',
                'ordering': ['-refill_date'],
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_gas', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remaining gas')),
                ('reading_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reading timestamp')),
                ('is_alert_triggered', models.BooleanField(default=False, verbose_name='alert triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_readings', to='mynewapp.gassensor')),
            ],
            options={
                'verbose_name': 'gas reading',
                'verbose_name_plural': 'gas readings',
                'ordering': ['-reading_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SHUT_OFF_VALVE', 'Shut Off Valve'), ('ACTIVATE_VENTILATION', 'Activate Ventilation'), ('SEND_ALERT', 'Send Alert'), ('CALL_EMERGENCY', 'Call Emergency Services')], max_length=50, verbose_name='action type')),
                ('action_status', models.CharField(choices=[('PENDING', 'Pending'), ('TRIGGERED', 'Triggered'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='initiated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_initiated', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_actions', to='mynewapp.gassensor')),
            ],
            options={
                'verbose_name': 'emergency action',
                'verbose_name_plural': 'emergency actions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('GAS_LEAK', 'Gas Leak'), ('LOW_BATTERY', 'Low Battery'), ('SENSOR_OFFLINE', 'Sensor Offline'), ('GAS_LEVEL_LOW', 'Gas Level Low')], max_length=50, verbose_name='alert type')),
                ('severity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, verbose_name='severity level')),
                ('alert_message', models.TextField(verbose_name='alert message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='mynewapp.gassensor')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state_province', models.CharField(max_length=100, verbose_name='state/province')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('is_primary_residence', models.BooleanField(default=False, verbose_name='primary residence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gassensor',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_sensors', to='mynewapp.house'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Mobile Push')], max_length=20, verbose_name='notification method')),
                ('recipient_address', models.CharField(max_length=255, verbose_name='recipient address')),
                ('notification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mynewapp.alert')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('BATTERY_REPLACEMENT', 'Battery Replacement'), ('CALIBRATION', 'Calibration'), ('CLEANING', 'Cleaning'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], max_length=50, verbose_name='maintenance type')),
                ('maintenance_notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='performed at')),
                ('next_maintenance_due', models.DateField(blank=True, null=True, verbose_name='next maintenance due')),
                ('performed_by', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='mynewapp.gassensor')),
            ],
            options={
                'verbose_name': 'maintenance record',
                'verbose_name_plural': 'maintenance records',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='mynewapp_cu_email_b14aab_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_admin'], name='mynewapp_cu_is_admi_ddfff4_idx'),
        ),
        migrations.AddIndex(
            model_name='gasreading',
            index=models.Index(fields=['sensor'], name='mynewapp_ga_sensor__f382c2_idx'),
        ),
        migrations.AddIndex(
            model_name='gasreading',
            index=models.Index(fields=['reading_timestamp'], name='mynewapp_ga_reading_117907_idx'),
        ),
        migrations.AddIndex(
            model_name='gasreading',
            index=models.Index(fields=['is_alert_triggered'], name='mynewapp_ga_is_aler_389ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user'], name='mynewapp_al_user_id_c58bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sensor'], name='mynewapp_al_sensor__6b1c92_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved'], name='mynewapp_al_is_reso_2099ca_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity_level'], name='mynewapp_al_severit_168a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['user'], name='mynewapp_ho_user_id_ef8263_idx'),
        ),
        migrations.AddIndex(
            model_name='gassensor',
            index=models.Index(fields=['house'], name='mynewapp_ga_house_i_4b9a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='gassensor',
            index=models.Index(fields=['is_active'], name='mynewapp_ga_is_acti_cb54d9_idx'),
        ),
        migrations.AddIndex(
            model_name='gassensor',
            index=models.Index(fields=['sensor_type'], name='mynewapp_ga_sensor__3752f7_idx'),
        ),
    ]
