# Generated by Django 5.2.1 on 2025-08-01 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gassensor',
            name='device_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='device API key'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='device ID'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='firmware version'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC address'),
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='battery_level_percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='battery level'),
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='installation date'),
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='last_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='last calibration date'),
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='serial number'),
        ),
    ]
