# Generated by Django 4.2.16 on 2026-03-24 20:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0002_add_device_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookableFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='food name')),
                ('estimated_gas_required', models.DecimalField(decimal_places=3, help_text='Estimated gas required to cook this food in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estimated gas required (kg)')),
                ('cooking_time_minutes', models.IntegerField(help_text='Estimated cooking time in minutes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='cooking time (minutes)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='image URL')),
            ],
            options={
                'verbose_name': 'cookable food',
                'verbose_name_plural': 'cookable foods',
                'ordering': ['estimated_gas_required'],
            },
        ),
        migrations.RemoveField(
            model_name='gassensor',
            name='device_api_key',
        ),
        migrations.RemoveField(
            model_name='gassensor',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='gassensor',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='gassensor',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='gassensor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gassensor',
            name='mac_address',
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='battery_level_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='battery level'),
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='installation_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 24, 20, 40, 27, 559061, tzinfo=datetime.timezone.utc), verbose_name='installation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='last_calibration_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 24, 20, 40, 52, 329269, tzinfo=datetime.timezone.utc), verbose_name='last calibration date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gassensor',
            name='serial_number',
            field=models.CharField(default='default', max_length=100, unique=True, verbose_name='serial number'),
            preserve_default=False,
        ),
    ]
