# Generated by Django 4.2.16 on 2026-03-26 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0003_cookablefood_remove_gassensor_device_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='store name')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='address')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='vendor_docs/birth_certs/', verbose_name='birth certificate')),
                ('identity_card', models.FileField(blank=True, null=True, upload_to='vendor_docs/id_cards/', verbose_name='identity card')),
                ('institution_document', models.FileField(blank=True, null=True, upload_to='vendor_docs/institution_docs/', verbose_name='institution document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendor profile',
                'verbose_name_plural': 'vendor profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BOCOM', 'Bocom'), ('TOTAL', 'Total'), ('GREEN_OIL', 'Green Oil'), ('SCTM', 'SCTM'), ('CAMGAZ', 'Camgaz'), ('TRADEX', 'Tradex'), ('MRS', 'MRS'), ('AFT', 'AFT'), ('OTHER', 'Other')], max_length=50, verbose_name='brand')),
                ('size', models.CharField(choices=[('SMALL_6KG', 'Small (6kg)'), ('MEDIUM_12_5KG', 'Medium (12.5kg)'), ('BIG_50KG', 'Big (50kg)')], max_length=50, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price (CFA)')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_bottles', to='mynewapp.vendorprofile')),
            ],
            options={
                'verbose_name': 'gas bottle',
                'verbose_name_plural': 'gas bottles',
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'brand', 'size')},
            },
        ),
    ]
