# Generated by Django 4.2.16 on 2026-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0004_vendorprofile_gasbottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_bottle_brand',
            field=models.CharField(choices=[('BOCOM', 'Bocom'), ('TOTAL', 'Total'), ('GREEN_OIL', 'Green Oil'), ('SCTM', 'SCTM'), ('CAMGAZ', 'Camgaz'), ('TRADEX', 'Tradex'), ('MRS', 'MRS'), ('AFT', 'AFT'), ('OTHER', 'Other')], default='TOTAL', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_bottle_size',
            field=models.CharField(choices=[('SMALL_6KG', 'Small (6kg)'), ('MEDIUM_12_5KG', 'Medium (12.5kg)'), ('BIG_50KG', 'Big (50kg)')], default='MEDIUM_12_5KG', max_length=20),
        ),
    ]
