# Generated by Django 4.2.16 on 2026-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0005_customuser_preferred_bottle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gas_capacity',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=5, verbose_name='gas capacity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tare_weight',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=5, verbose_name='tare weight'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_bottle_brand',
            field=models.CharField(choices=[('SCTM', 'SCTM'), ('TOTAL_ENERGIES', 'TotalEnergies'), ('TRADEX', 'Tradex'), ('STAR_GAS', 'StarGas'), ('AZA_MRS', 'Aza Gas / MRS'), ('GLOCAL_GAS', 'Glocal Gas'), ('BOCOM', 'Bocom'), ('TOTAL', 'Total'), ('GREEN_OIL', 'Green Oil'), ('CAMGAZ', 'Camgaz'), ('MRS', 'MRS'), ('AFT', 'AFT'), ('OTHER', 'Other')], default='TOTAL_ENERGIES', max_length=50),
        ),
        migrations.AlterField(
            model_name='gasbottle',
            name='brand',
            field=models.CharField(choices=[('SCTM', 'SCTM'), ('TOTAL_ENERGIES', 'TotalEnergies'), ('TRADEX', 'Tradex'), ('STAR_GAS', 'StarGas'), ('AZA_MRS', 'Aza Gas / MRS'), ('GLOCAL_GAS', 'Glocal Gas'), ('BOCOM', 'Bocom'), ('TOTAL', 'Total'), ('GREEN_OIL', 'Green Oil'), ('CAMGAZ', 'Camgaz'), ('MRS', 'MRS'), ('AFT', 'AFT'), ('OTHER', 'Other')], max_length=50, verbose_name='brand'),
        ),
    ]
