# Generated by Django 4.2.16 on 2026-08-11 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0006_customuser_gas_capacity_customuser_tare_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_person',
            field=models.BooleanField(default=False, verbose_name='delivery person'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('delivery_address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_ordered', to=settings.AUTH_USER_MODEL)),
                ('delivery_person', models.ForeignKey(blank=True, limit_choices_to={'is_delivery_person': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_handled', to=settings.AUTH_USER_MODEL)),
                ('gas_bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mynewapp.gasbottle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_received', to='mynewapp.vendorprofile')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
