# Generated by Django 4.2.16 on 2026-09-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0007_customuser_is_delivery_person_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasreading',
            name='raw_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='raw weight'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='current_valve_state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=10, verbose_name='current valve state'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='desired_alarm_state',
            field=models.CharField(choices=[('ARM', 'Arm'), ('SILENCE', 'Silence')], default='ARM', max_length=10, verbose_name='desired alarm state'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='desired_valve_state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=10, verbose_name='desired valve state'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='is_alarm_silenced',
            field=models.BooleanField(default=False, verbose_name='alarm silenced'),
        ),
        migrations.AddField(
            model_name='gassensor',
            name='raw_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='raw weight'),
        ),
    ]
