# Generated by Django 4.2.16 on 2026-09-26 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def preserve_existing_vendor_approvals(apps, schema_editor):
    VendorProfile = apps.get_model("mynewapp", "VendorProfile")
    VendorProfile.objects.filter(is_approved=True).update(application_status="APPROVED")


def reverse_vendor_approvals(apps, schema_editor):
    VendorProfile = apps.get_model("mynewapp", "VendorProfile")
    VendorProfile.objects.update(application_status="PENDING")


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0008_gasreading_raw_weight_gassensor_current_valve_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='fulfillment_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Customer pickup')], default='DELIVERY', max_length=12),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='additional_document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/supporting_docs/', verbose_name='supporting document'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='application_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tax_payment_document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/tax_proofs/', verbose_name='tax payment proof'),
        ),
        migrations.RunPython(preserve_existing_vendor_approvals, reverse_vendor_approvals),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryPersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_card', models.FileField(blank=True, null=True, upload_to='delivery_docs/id_cards/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='delivery_docs/supporting_docs/')),
                ('application_status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delivery_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
