# Generated by Django 4.2.16 on 2026-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0009_delivery_fulfillment_method_delivery_stock_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_operator',
            field=models.CharField(blank=True, choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(choices=[('INITIATING', 'Starting payment'), ('PENDING', 'Waiting for payment'), ('PAID', 'Paid'), ('FAILED', 'Payment failed'), ('UNKNOWN', 'Payment status unknown')], db_index=True, default='PAID', max_length=12),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
