# Generated by Django 4.2.16 on 2026-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0010_delivery_delivery_fee_delivery_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(choices=[('INITIATING', 'Starting payment'), ('PENDING', 'Waiting for payment'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('FAILED', 'Payment failed'), ('UNKNOWN', 'Payment status unknown')], db_index=True, default='PAID', max_length=12),
        ),
    ]
