# Generated by Django 4.2.16 on 2026-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0011_alter_delivery_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='client_confirmed_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_confirmed_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
