# Generated by Django 4.2.16 on 2026-10-09 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0012_delivery_confirmation_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Professional')], default='free', max_length=12),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Professional')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_operator', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo')], max_length=20)),
                ('payer_phone', models.CharField(max_length=16)),
                ('payment_status', models.CharField(choices=[('INITIATING', 'Starting payment'), ('PENDING', 'Waiting for payment'), ('PAID', 'Paid'), ('FAILED', 'Payment failed'), ('UNKNOWN', 'Payment status unknown')], db_index=True, default='INITIATING', max_length=12)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
