# Generated by Django 4.2.16 on 2026-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0013_customuser_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payer_phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
